### ISSUE TITLE
BitPacker4x::num_bits_sorted SIGSEGV on empty arrays

### ISSUE THREAD

**Issue by Kerollmops** [tantivy-search/bitpacking#23]
When called with an empty array the `num_bits_sorted` triggers a segfault, this is not specified anywhere that the array must not be empty (or do I missed it?).

```rust
fn num_bits_sorted(&self, initial: u32, decompressed: &[u32]) -> u8 {
     unsafe { scalar::UnsafeBitPackerImpl::num_bits_sorted(initial, decompressed) }
}
```

If you want to easily reproduce the bug just create an empty `vec![]` and give it to `BitPacker4x::num_bits_sorted`.

**Comment by fulmicoton** [comment]
Good point! Let's fix this.

**Comment by fulmicoton** [comment]
@kerollmops also, if you intend to use bitpacking for meili, make sure to bitpack on blocks with a limit size. (typically 128 ints.)

**Comment by Kerollmops** [comment]
@fulmicoton, what do you mean by a block with a limit size?

**Comment by fulmicoton** [comment]
Yes. I'll update doc and add an assert.

Your first block required numbits=10 and the second one numbits=15.
The second block was ignored, so only 10 bits were used. The first delta for which it was insufficient happened to be exactly 2^10=1024 but that was a coincidence.

**Comment by Kerollmops** [comment]
I have computed and added the `num_bits` values in fron t of all the numbers blocks.
Thank you! This is fixed now!
